import type { Metadata } from "next"
import { Noto_Sans_JP, Source_Code_Pro } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { Nav } from "@/components/nav"
import { cn } from "@/lib/utils"
import { sourceCode } from "@/lib/css-font"

const notoSansJP = Noto_Sans_JP({
    variable: "--noto-sans-jp",
    subsets: ["latin"],
})

const sourceCodePro = Source_Code_Pro({
    variable: "--source-code-pro",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="ja" suppressHydrationWarning>
            <body
                className={`${notoSansJP.className} ${notoSansJP.variable} ${sourceCodePro.variable} antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange>
                    <div className="min-h-screen flex flex-col">
                        <Nav />

                        <main className="flex flex-grow flex-col justify-center items-center w-screen my-4">
                            {children}
                        </main>

                        <footer className="mt-auto">
                            <div className="flex justify-center items-center py-4">
                                <p
                                    className={cn(
                                        "md:text-sm text-xs",
                                        sourceCode,
                                    )}>
                                    (C) 2025 copyright
                                </p>
                            </div>
                        </footer>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
